dist: trusty
sudo: false
matrix:
  include:
  - language: objective-c
    osx_image: xcode10.2
    before_install:
    - date
    - export TZ=America/New_York
    - date
    before_script:
    - echo ${TZ}
    script:
    - cd SeptaJSON
    - xcodebuild clean build -project SeptaJSON.xcodeproj -scheme SeptaJSON CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' -quiet
    - xcodebuild test -project SeptaJSON.xcodeproj -scheme SeptaJSON -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2'  -enableCodeCoverage  YES -quiet
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    







