
disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - line_length
 - force_try
 - force_cast
 - operator_whitespace
 - variable_name
 - type_name
 - cyclomatic_complexity
 - function_body_length
 - for_where
 - xctfail_message
 - todo
 - nesting

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 